export const PRODUCTION_CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "script-src 'self' https://www.paypal.com https://www.sandbox.paypal.com https://www.paypalobjects.com",
  "script-src-attr 'none'",
  "style-src 'self'",
  "style-src-attr 'unsafe-inline'",
  "font-src 'self' data:",
  "img-src 'self' data: blob: https://www.paypal.com https://www.sandbox.paypal.com https://www.paypalobjects.com https://uploadthing.com https://*.uploadthing.com https://ufs.sh https://*.ufs.sh https://utfs.io https://*.utfs.io",
  "media-src 'self' https://uploadthing.com https://*.uploadthing.com https://ufs.sh https://*.ufs.sh https://utfs.io https://*.utfs.io",
  "connect-src 'self' wss://*.livekit.cloud https://*.livekit.cloud https://uploadthing.com https://*.uploadthing.com https://ufs.sh https://*.ufs.sh https://utfs.io https://*.utfs.io https://api-m.sandbox.paypal.com https://api-m.paypal.com https://www.paypal.com https://www.sandbox.paypal.com https://axelmond.com https://www.axelmond.com wss://axelmond.com wss://www.axelmond.com",
  "frame-src 'self' https://www.paypal.com https://www.sandbox.paypal.com https://checkout.paypal.com https://checkout.sandbox.paypal.com https://uploadthing.com https://*.uploadthing.com https://ufs.sh https://*.ufs.sh https://utfs.io https://*.utfs.io https://www.google.com https://maps.google.com",
  "child-src 'self' https://www.paypal.com https://www.sandbox.paypal.com https://checkout.paypal.com https://checkout.sandbox.paypal.com https://uploadthing.com https://*.uploadthing.com https://ufs.sh https://*.ufs.sh https://utfs.io https://*.utfs.io https://www.google.com https://maps.google.com",
  "worker-src 'self' blob:",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self' https://www.paypal.com https://www.sandbox.paypal.com",
  "frame-ancestors 'self'",
  "upgrade-insecure-requests",
].join("; ");
