import type { Dispatch, SetStateAction } from "react";
import type { AdminAcademicTaxonomyViewProps } from "./AdminAcademicTaxonomyView";
import type { Course, ContentSection, FacultyDomain, LessonContent } from "../../types";

export interface TeacherCurriculumViewProps extends AdminAcademicTaxonomyViewProps {
  canManageAcademicTaxonomy: boolean;
  domains: FacultyDomain[];
  activeCurriculumStep: number;
  setActiveCurriculumStep: (value: number) => void;
  selectedChapterId: string;
  setSelectedChapterId: (value: string) => void;
  selectedPartieId: string;
  setSelectedPartieId: (value: string) => void;
  newSectionMode: "chapter" | "part" | "subpart";
  setNewSectionMode: (value: "chapter" | "part" | "subpart") => void;
  uploadChapterId: string;
  setUploadChapterId: (value: string) => void;
  uploadPartId: string;
  setUploadPartId: (value: string) => void;
  uploadSubpartId: string;
  setUploadSubpartId: (value: string) => void;
  quizChapterId: string;
  setQuizChapterId: (value: string) => void;
  quizPartId: string;
  setQuizPartId: (value: string) => void;
  quizSubpartId: string;
  setQuizSubpartId: (value: string) => void;
  curriculumSuccessMsg: string;
  curriculumErrorMsg: string;
  newCourseTitle: string;
  setNewCourseTitle: (value: string) => void;
  newCourseDescription: string;
  setNewCourseDescription: (value: string) => void;
  newCourseDisciplineId: number;
  setNewCourseDisciplineId: (value: number) => void;
  newCourseCredits: string;
  setNewCourseCredits: (value: string) => void;
  newCourseDuration: string;
  setNewCourseDuration: (value: string) => void;
  newCoursePrice: string;
  setNewCoursePrice: (value: string) => void;
  newCoursePublished: boolean;
  setNewCoursePublished: (value: boolean) => void;
  newSectionCourseId: number;
  newSectionTitle: string;
  setNewSectionTitle: (value: string) => void;
  newSectionParentId: string;
  setNewSectionParentId: (value: string) => void;
  newSectionPublished: boolean;
  setNewSectionPublished: (value: boolean) => void;
  uploadSectionId: string;
  setUploadSectionId: (value: string) => void;
  uploadTitle: string;
  setUploadTitle: (value: string) => void;
  uploadType: "VIDEO" | "PDF" | "IMAGE";
  setUploadType: (value: "VIDEO" | "PDF" | "IMAGE") => void;
  uploadFile: File | null;
  setUploadFile: (value: File | null) => void;
  uploadPublished: boolean;
  setUploadPublished: (value: boolean) => void;
  uploadStatusMsg: string;
  editingCourse: Course | null;
  setEditingCourse: (value: Course | null) => void;
  editCourseForm: {
    title: string;
    description: string;
    level: string;
    duration: string;
    credits: string;
    disciplineId: number;
    price: string;
  };
  setEditCourseForm: Dispatch<
    SetStateAction<{
      title: string;
      description: string;
      level: string;
      duration: string;
      credits: string;
      disciplineId: number;
      price: string;
    }>
  >;

  teacherQuizzes: any[];
  selectedQuizDetail: any | null;
  quizCourseId: number;
  newQuizTitle: string;
  setNewQuizTitle: (value: string) => void;
  selectedQuizId: string;
  setSelectedQuizId: (value: string) => void;
  newQuestionText: string;
  setNewQuestionText: (value: string) => void;
  newQuestionOptions: string[];
  setNewQuestionOptions: Dispatch<SetStateAction<string[]>>;

  newQuestionAnswer: string;
  setNewQuestionAnswer: (value: string) => void;
  newQuestionExplanation: string;
  setNewQuestionExplanation: (value: string) => void;
  quizManagerMsg: string;
  quizManagerError: string;
  allDisciplines: FacultyDomain["disciplines"][number][];
  managedCourses: Course[];
  managedCourse: Course | null;
  managedSections: (ContentSection & { depth?: number })[];
  chapterSections: (ContentSection & { depth?: number })[];
  uploadPartOptions: (ContentSection & { depth?: number })[];
  selectedManagedContents: LessonContent[];
  handleSetUploadSectionId: (sectionId: string) => void;
  showCurriculumSuccess: (message: string) => void;
  showCurriculumError: (message: string) => void;
  handleCreateCourse: (...args: any[]) => void | Promise<void>;
  handleCreateSection: (...args: any[]) => void | Promise<void>;
  handleUploadLessonAsset: (...args: any[]) => void | Promise<void>;
  handleSelectManagedCourse: (courseId: number) => Promise<void>;
  loadTeacherQuizzes: (courseId?: number) => void | Promise<void>;
  handleCreateQuiz: (...args: any[]) => void | Promise<void>;
  handleAddQuestion: (...args: any[]) => void | Promise<void>;
  handleDeleteQuestion: (...args: any[]) => void | Promise<void>;
  handleUpdateCourseDetails: (...args: any[]) => void | Promise<void>;
  handleSaveEditCourse: (...args: any[]) => void | Promise<void>;
  handleToggleCoursePublished: (...args: any[]) => void | Promise<void>;
  handleDeleteCourse: (...args: any[]) => void | Promise<void>;
  handleUpdateSectionTitle: (...args: any[]) => void | Promise<void>;
  handleToggleSectionPublished: (...args: any[]) => void | Promise<void>;
  handleDeleteSection: (...args: any[]) => void | Promise<void>;
  handleAddChildSection: (...args: any[]) => void | Promise<void>;
  handleToggleContentPublished: (...args: any[]) => void | Promise<void>;
  handleDeleteLessonContent: (...args: any[]) => void | Promise<void>;
}
